
import os
import streamlit as st
from openai import OpenAI
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import tempfile
import re

st.set_page_config(page_title="AI Company Finder v4.4", page_icon=":robot_face:", layout="centered")

api_key = os.environ.get("OPENAI_API_KEY")
if not api_key:
    st.error("Missing OpenAI API key. Add it under Streamlit Cloud → Settings → Secrets as 'OPENAI_API_KEY'.")
    st.stop()

client = OpenAI(api_key=api_key)

def get_company_info(company_name, mode="full"):
    if mode == "full":
        prompt = f'''
You are a fact-seeking AI assistant with access to online sources.
Find and summarise the following for the company '{company_name}':
1. What types of products do they develop?
2. Which three products are their most well-known ones? (include image links if available)
3. What is their newest product and launch date?
4. How many people work in their product development or R&D departments?
5. In which countries are their development departments located?
6. Do they use external design agencies or consultants?
7. Based on their profile, which specific mix of services from www.mjid.dk (Concept Design, Industrial Design, Mechanical Engineering, Prototype Building, User Testing, Innovation Strategy) would create the highest value, and why?
8. What could be the best reason for not engaging with MJID.dk?
9. What are the 3 best counter arguments MJID.dk could use?
10. Who should MJID.dk contact to discuss collaboration? (name, title, email, phone, LinkedIn if available)
'''
    else:
        prompt = f'''
Summarise the company '{company_name}' in 1-2 short paragraphs covering:
- product types, top products, newest product, R&D size and locations
- use of external design agencies
- MJID.dk fit, main objection, counter arguments, and contacts.
'''

    response = client.responses.create(
    model="gpt-5",
    input=f"{prompt}\n\nAnswer based on the most up-to-date and verifiable online information you know. Be concise and factual."
)

    return response.output_text

def generate_pdf_v4_4(company_name, text):
    styles = getSampleStyleSheet()
    link_style = ParagraphStyle('link_style', parent=styles['Normal'], textColor='blue', underline=True)
    doc = SimpleDocTemplate(tempfile.NamedTemporaryFile(delete=False, suffix=".pdf").name,
                            pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)

    sections = {"Company Overview": [], "R&D": [], "External Design Use": [],
                "MJID.dk Service Fit": [], "Potential Objection": [],
                "Counter-Arguments": [], "Recommended Contacts": []}

    mapping = {"products": "Company Overview", "r&d": "R&D", "development departments": "R&D",
               "external design": "External Design Use", "mjid.dk": "MJID.dk Service Fit",
               "objection": "Potential Objection", "counter": "Counter-Arguments", "contact": "Recommended Contacts"}

    for line in text.splitlines():
        assigned = False
        for keyword, section in mapping.items():
            if keyword in line.lower():
                sections[section].append(line)
                assigned = True
                break
        if not assigned:
            sections["Company Overview"].append(line)

    elements = [Paragraph("<b>AI Company Strategy Report</b>", styles["Title"]),
                Spacer(1, 0.5*cm),
                Paragraph(f"<b>Company:</b> {company_name}", styles["Heading2"]),
                Spacer(1, 0.3*cm)]

    for title, content_lines in sections.items():
        if not content_lines:
            continue
        elements.append(Paragraph(f"<b>{title}</b>", styles["Heading3"]))
        elements.append(Spacer(1, 0.2*cm))
        if title == "Recommended Contacts":
            def hyperlink_text(line):
                line = re.sub(r'(\S+@\S+\.\S+)', r'<a href="mailto:\1">\1</a>', line)
                line = re.sub(r'(https?://[^\s]+linkedin[^\s]*)', r'<a href="\1">\1</a>', line)
                return line
            content_lines = [hyperlink_text(l) for l in content_lines if l.strip()]
            elements.append(Paragraph("<br/>".join(content_lines), link_style))
        else:
            elements.append(Paragraph("<br/>".join(content_lines), styles["Normal"]))
        elements.append(Spacer(1, 0.3*cm))

    elements.append(Paragraph("<i>Automatically generated by OpenAI and Streamlit</i>", styles["Italic"]))
    doc.build(elements)
    return doc.filename

st.title("AI Company Finder v4.4")
st.write("Retrieve company data, product info, R&D, and collaboration analysis for MJID.dk.")
company_name = st.text_input("Enter company name", placeholder="e.g. Grundfos, LEGO, Danfoss...")
mode = st.radio("Select report mode:", ["Full detail", "Short summary"], horizontal=True)

if st.button("Search", use_container_width=True):
    if not company_name.strip():
        st.warning("Please enter a company name first.")
    else:
        with st.spinner("Searching online..."):
            try:
                mode_sel = "full" if mode == "Full detail" else "short"
                answer = get_company_info(company_name, mode_sel)
                st.markdown(answer)
                if mode_sel == "full":
                    links = re.findall(r'(https?://\S+\.(?:jpg|png|jpeg|webp))', answer)
                    for link in links[:3]:
                        st.image(link, width=200)
                pdf_path = generate_pdf_v4_4(company_name, answer)
                with open(pdf_path, "rb") as f:
                    st.download_button("📄 Download PDF", data=f, file_name=f"{company_name}_AI_Report.pdf", mime="application/pdf")
            except Exception as e:
                st.error(str(e))
